// auto-generated by circomkit
pragma circom 2.2.3;

include "../prepared_multi_link.circom";

component main {public[expectedDeviceKeyX, expectedDeviceKeyY, expectedClaimValues]} = PreparedMultiLink(6);
