// auto-generated by circomkit
pragma circom 2.2.3;

include "../show.circom";

component main {public[deviceKeyX, deviceKeyY, messageHash, predicateLen, predicateClaimRefs, predicateOps, predicateRhsIsRef, predicateRhsValues, tokenTypes, tokenValues, exprLen]} = Show(4, 2, 8, 64);
